package main

import "fmt"

func printHelp() {
	fmt.Printf("Fastls MITM Proxy - 中间人代理服务器\n\n")
	fmt.Printf("用法:\n")
	fmt.Printf("  mitm [选项]\n\n")
	fmt.Printf("选项:\n")
	fmt.Printf("  -addr string\n")
	fmt.Printf("        监听地址 (默认: \":8888\")\n")
	fmt.Printf("        示例: -addr \":8888\" 或 -addr \"0.0.0.0:8888\"\n\n")
	fmt.Printf("  -browser string\n")
	fmt.Printf("        浏览器类型 (默认: \"chrome142\")\n")
	fmt.Printf("        可选值: chrome, chrome120, chrome142, chromium, edge, firefox, safari, opera\n\n")
	fmt.Printf("  -ja3 string\n")
	fmt.Printf("        自定义JA3指纹字符串 (如果指定，将忽略browser参数)\n\n")
	fmt.Printf("  -ja4r string\n")
	fmt.Printf("        自定义JA4R指纹字符串 (如果指定，将忽略browser参数)\n\n")
	fmt.Printf("  -ca-cert string\n")
	fmt.Printf("        CA证书文件路径 (默认: \"mitm-ca-cert.pem\")\n\n")
	fmt.Printf("  -ca-key string\n")
	fmt.Printf("        CA私钥文件路径 (默认: \"mitm-ca-key.pem\")\n\n")
	fmt.Printf("  -disable-connect\n")
	fmt.Printf("        禁用 CONNECT 隧道请求，只支持 HTTP 代理方式\n\n")
	fmt.Printf("  -debug\n")
	fmt.Printf("        启用 Debug 模式，显示详细的调试日志\n\n")
	fmt.Printf("  -version\n")
	fmt.Printf("        显示版本信息并退出\n\n")
	fmt.Printf("  -help, -h\n")
	fmt.Printf("        显示此帮助信息并退出\n\n")
	fmt.Printf("请求头配置 (X-Mitm-*):\n")
	fmt.Printf("  可以通过请求头动态指定指纹配置，优先级高于启动参数:\n")
	fmt.Printf("  X-Mitm-Browser: 浏览器类型 (chrome, chrome120, chrome142, chromium, edge, firefox, safari, opera)\n")
	fmt.Printf("  X-Mitm-Ja3:     JA3指纹字符串\n")
	fmt.Printf("  X-Mitm-Ja4r:    JA4R指纹字符串\n\n")
	fmt.Printf("示例:\n")
	fmt.Printf("  mitm -addr :8888\n")
	fmt.Printf("  mitm -addr :8888 -browser chrome142 -debug\n")
	fmt.Printf("  mitm -addr :8888 -ja3 \"771,4865-4866-4867...\"\n")
	fmt.Printf("  curl -x http://127.0.0.1:8888 -H \"X-Mitm-Browser: chrome142\" https://example.com\n")
	fmt.Printf("  curl -x http://127.0.0.1:8888 -H \"X-Mitm-Ja3: 771,4865-4866-4867...\" https://example.com\n")
	fmt.Printf("  mitm -version\n")
	fmt.Printf("  mitm -help\n\n")
	fmt.Printf("更多信息请访问: https://github.com/FastTLS/fastls\n")
}
